<a href="https://colab.research.google.com/github/preethyannthomas/Python-Libraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy
numpy.__version__

'1.22.4'

In [7]:
import numpy as np

In [3]:
lst = [1,2,3]
np.array(lst)

array([1, 2, 3])

In [4]:
np.array(lst,dtype='float32')
#set data type using dtype

array([1., 2., 3.], dtype=float32)

In [6]:
np.zeros(10,dtype=int)
# filled with zeroes first parameter, length

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
np.arange(0,20,2)
# start:0 end:20 increment:2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
 np.linspace(0, 1, 5)
 # linspace is used to evenly distribute values between intervals to specific number

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.random((3,3))

array([[0.51484163, 0.89373898, 0.41284683],
       [0.18520701, 0.03242453, 0.03687508],
       [0.81402938, 0.7738179 , 0.2238004 ]])

In [15]:
np.random.randint(0,10,(3,3))

array([[9, 0, 5],
       [1, 3, 7],
       [0, 4, 4]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

NumPy Array Attributes


In [8]:
np.random.seed(0) # seed for reproducacibility, for each time it returns same random value
x1 = np.random.randint(10,size=3)

In [11]:
print("x1 ndim:",x1.ndim)
print("x1 shape:",x1.shape)
print("x1 size:",x1.size)

x1 ndim: 1
x1 shape: (3,)
x1 size: 3


In [12]:
x1.dtype

dtype('int64')

In [13]:
print("itemsize:",x1.itemsize,"bytes") # space required in memory by each
print("nbytes:",x1.nbytes,"bytes") # total space

itemsize: 8 bytes
nbytes: 24 bytes


Array Indexing

In [14]:
x1[0]

5

In [15]:
x1

array([5, 0, 3])

In [16]:
x1[-1]

3

In [18]:
x2 = np.random.randint(1,10,size=(3,3))

In [19]:
x2

array([[4, 8, 4],
       [6, 3, 5],
       [8, 7, 9]])

In [21]:
x2[0,2]

4

In [22]:
x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[4:7])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [23]:
#Multidimensional Subarray
print(x2)
print(x2[:1,:2])
print(x2[:2,:1])

[[4 8 4]
 [6 3 5]
 [8 7 9]]
[[4 8]]
[[4]
 [6]]


Array Concatenation and Splitting

In [25]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [28]:
a=np.array([[1,2,3],[4,5,6]]) #2D
np.concatenate([a,a]) # stack horizontally, axis = 0


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
np.concatenate([a,a],axis=1) # stack vertically

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
#To concatenate array of different dimensions together we use vstack and hstack
np.vstack([x,a])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
x = np.array([[99],[99]])
np.hstack([a,x])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [35]:
x=[1,2,3,4,5,6,7,8,9,110]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [  6   7   8   9 110]


In [36]:
 grid = np.arange(16).reshape((4,4))
 print(grid)
 upper,lower = np.vsplit(grid, [2])
 print(upper)
 print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [37]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
